/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HotseatRouteImport } from './routes/hotseat'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as ApiRtcRouteImport } from './routes/api/rtc'
import { Route as PlayCodeRouteImport } from './routes/play.$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HotseatRoute = HotseatRouteImport.update({
  id: '/hotseat',
  path: '/hotseat',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRtcRoute = ApiRtcRouteImport.update({
  id: '/api/rtc',
  path: '/api/rtc',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayCodeRoute = PlayCodeRouteImport.update({
  id: '/play/$code',
  path: '/play/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hotseat': typeof HotseatRoute
  '/practice': typeof PracticeRoute
  '/rules': typeof RulesRoute
  '/api/rtc': typeof ApiRtcRoute
  '/play/$code': typeof PlayCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hotseat': typeof HotseatRoute
  '/practice': typeof PracticeRoute
  '/rules': typeof RulesRoute
  '/api/rtc': typeof ApiRtcRoute
  '/play/$code': typeof PlayCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hotseat': typeof HotseatRoute
  '/practice': typeof PracticeRoute
  '/rules': typeof RulesRoute
  '/api/rtc': typeof ApiRtcRoute
  '/play/$code': typeof PlayCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/hotseat' | '/practice' | '/rules' | '/api/rtc' | '/play/$code'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/hotseat' | '/practice' | '/rules' | '/api/rtc' | '/play/$code'
  id:
    | '__root__'
    | '/'
    | '/hotseat'
    | '/practice'
    | '/rules'
    | '/api/rtc'
    | '/play/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HotseatRoute: typeof HotseatRoute
  PracticeRoute: typeof PracticeRoute
  RulesRoute: typeof RulesRoute
  ApiRtcRoute: typeof ApiRtcRoute
  PlayCodeRoute: typeof PlayCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotseat': {
      id: '/hotseat'
      path: '/hotseat'
      fullPath: '/hotseat'
      preLoaderRoute: typeof HotseatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rtc': {
      id: '/api/rtc'
      path: '/api/rtc'
      fullPath: '/api/rtc'
      preLoaderRoute: typeof ApiRtcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$code': {
      id: '/play/$code'
      path: '/play/$code'
      fullPath: '/play/$code'
      preLoaderRoute: typeof PlayCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HotseatRoute: HotseatRoute,
  PracticeRoute: PracticeRoute,
  RulesRoute: RulesRoute,
  ApiRtcRoute: ApiRtcRoute,
  PlayCodeRoute: PlayCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
